version: "3"
services:
  mysql:
    image: mysql:5.7.24
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: local
      MYSQL_DATABASE: local
      MYSQL_USER: local
      MYSQL_PASSWORD: local
